// noise-worklet.js — AudioWorklet Processor
// Runs in the dedicated audio rendering thread for glitch-free noise generation.
'use strict';

class NoiseProcessor extends AudioWorkletProcessor {
  constructor(options) {
    super(options);

    this._type = options?.processorOptions?.type ?? 'white';

    // ── Pink noise state (Paul Kellet's algorithm) ─────────────────────────
    this._b0 = this._b1 = this._b2 = 0;
    this._b3 = this._b4 = this._b5 = 0;
    this._b6 = 0;

    // ── Brown noise state ──────────────────────────────────────────────────
    this._brownLast = 0;

    // ── Blue / Violet noise state ──────────────────────────────────────────
    this._prevW  = 0; // previous white sample  (for blue)
    this._prevD1 = 0; // previous first diff    (for violet)

    // Accept runtime type changes from the renderer
    this.port.onmessage = ({ data }) => {
      if (data?.type) {
        this._type = data.type;
        this._resetState();
      }
    };
  }

  _resetState() {
    this._b0 = this._b1 = this._b2 = 0;
    this._b3 = this._b4 = this._b5 = 0;
    this._b6 = 0;
    this._brownLast = 0;
    this._prevW = this._prevD1 = 0;
  }

  process(_inputs, outputs) {
    const out = outputs[0];
    const ch0 = out[0]; // left
    const ch1 = out[1]; // right

    if (!ch0) return true;

    for (let i = 0; i < ch0.length; i++) {
      ch0[i] = this._next();
    }

    // Copy left → right (mono-to-stereo)
    if (ch1) ch1.set(ch0);

    return true; // keep alive
  }

  _next() {
    switch (this._type) {
      case 'white':  return this._white();
      case 'pink':   return this._pink();
      case 'brown':  return this._brown();
      case 'blue':   return this._blue();
      case 'violet': return this._violet();
      default:       return this._white();
    }
  }

  // ── White noise ────────────────────────────────────────────────────────────
  // Equal energy at every frequency (flat spectrum).
  _white() {
    return Math.random() * 2 - 1;
  }

  // ── Pink noise ─────────────────────────────────────────────────────────────
  // Paul Kellet's refined algorithm — -3 dB/octave roll-off.
  // Widely used; perceptually balanced; great for sound masking.
  _pink() {
    const w = Math.random() * 2 - 1;
    this._b0 =  0.99886 * this._b0 + w * 0.0555179;
    this._b1 =  0.99332 * this._b1 + w * 0.0750759;
    this._b2 =  0.96900 * this._b2 + w * 0.1538520;
    this._b3 =  0.86650 * this._b3 + w * 0.3104856;
    this._b4 =  0.55000 * this._b4 + w * 0.5329522;
    this._b5 = -0.76160 * this._b5 - w * 0.0168980;
    const out = this._b0 + this._b1 + this._b2 + this._b3
              + this._b4 + this._b5 + this._b6 + w * 0.5362;
    this._b6 = w * 0.115926;
    return out * 0.11; // normalise to ~[-1, 1]
  }

  // ── Brown (Brownian / Red) noise ───────────────────────────────────────────
  // -6 dB/octave roll-off — deepest, most "rumbling" character.
  // Generated by integrating white noise (random walk).
  _brown() {
    const w = Math.random() * 2 - 1;
    // Mean-reverting walk (prevents DC drift to ±∞)
    this._brownLast = (this._brownLast + 0.02 * w) / 1.02;
    return this._brownLast * 3.5; // scale to roughly [-1, 1]
  }

  // ── Blue noise ─────────────────────────────────────────────────────────────
  // +3 dB/octave — first-order derivative of white noise.
  // Emphasises high frequencies; sounds airy/hissy.
  _blue() {
    const w   = Math.random() * 2 - 1;
    const out = (w - this._prevW) * 0.5; // diff + normalise
    this._prevW = w;
    return out;
  }

  // ── Violet noise ───────────────────────────────────────────────────────────
  // +6 dB/octave — second-order derivative of white noise.
  // Very high-frequency emphasis; extremely hissy/sharp.
  _violet() {
    const w   = Math.random() * 2 - 1;
    const d1  = w - this._prevW;
    const out = (d1 - this._prevD1) * 0.25; // diff + normalise
    this._prevW  = w;
    this._prevD1 = d1;
    return out;
  }
}

registerProcessor('noise-processor', NoiseProcessor);
